name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.17', '1.18' ]
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test ./... -v
